### PR TITLE
Deprecation/inactivation of run_Fastq_Multx

### PR DESCRIPTION
**Pull request by zhlu9890**
For https://kbase-jira.atlassian.net/browse/PTV-1445, I took the PR #12, and updated Dockerfile to use latest image and adjusted .travis file accordingly.

### CODE REVIEW

**Comment by sychan** [comment]
@Tianhao-Gu Can you take a look at this PR and make sure it looks ok?

**Review by Tianhao-Gu — APPROVED** [review]
@zhlu9890 could you bump version? Other than that, it looks 👍  to me.

**Comment by zhlu9890** [comment]
I bumped the version in `kbase.yml` to the same as in `RELEASE_NOTES.md`

**Review by Tianhao-Gu — APPROVED** [review]
💯

**Review by psdehal — APPROVED** [review]
looks fine

**Pull request merged**
