### PR TITLE
Added Citations

### PR DESCRIPTION
**Pull request by mclark58**
Added KBase paper citation in PLOS format, increased patch number by 1, moved additional references to correct location, created RELEASE_NOTES.md file

### CODE REVIEW

**Comment by dcchivian** [comment]
@sychan can you take a look?  travis-ci build failing with message:
-------------------------------------------------------------------
4.06s$ git clone --depth=50 https://github.com/kbaseapps/kb_ea_utils.git kbaseapps/kb_ea_utils
Cloning into 'kbaseapps/kb_ea_utils'...
remote: Enumerating objects: 571, done.
remote: Counting objects:  69% (394/571)  remote: Counting objects: 100% (571/571), done.
remote: Compressing objects: 100% (209/209), done.
remote: Total 571 (delta 322), reused 551 (delta 311), pack-reused 0
Receiving objects: 100% (571/571), 35.40 MiB | 14.50 MiB/s, done.
Resolving deltas: 100% (322/322), done.
$ cd kbaseapps/kb_ea_utils
0.30s$ git fetch origin +refs/pull/7/merge:
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 14 (delta 5), reused 14 (delta 5), pack-reused 0
Unpacking objects: 100% (14/14), done.
From https://github.com/kbaseapps/kb_ea_utils
 * branch            refs/pull/7/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
rvm
6.52s$ rvm use default
Using /home/travis/.rvm/gems/ruby-2.4.1
** Updating RubyGems to the latest version for security reasons. **
** If you need an older version, you can downgrade with 'gem update --system OLD_VERSION'. **
ruby.versions
$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
$ rvm --version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 1.16.2
$ gem --version
2.7.7
No Gemfile found, skipping bundle install
0.25s$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-2.4.1@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
Done. Your build exited with 1.
-------------------------------------------------------------------

**Comment by mclark58** [comment]
@sychan could you look over my changes and merge if all looks well? Please and thank you!

**Comment by mclark58** [comment]
@sychan I noticed my forked repo now says that it is 1 commit ahead and 1 commit behind. Do I need to delete this PR, get my repo even with the master, and resubmit a PR? This is the last repo that needs merging before all the apps can be rereleased. Thanks!

**Comment by sychan** [comment]
@mclark58 What was happening is that a bogus travis.yml file was had been committed to the repo in the past, which was causing travis-ci to break. I fixed that after you had made your citation updates. What you really want to do is to pull in the updates from the master branch (so that you are not longer 1 commit behind the source repo), and then push them back to your repo. This will enable travis-ci to run properly, validating your updates before doing the merge.
But I'm going to merge the PR just to wrap things up.

**Comment by mclark58** [comment]
@sychan thank you!

**Pull request merged**
